/*
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(250) NOT NULL UNIQUE,
    password VARCHAR(250) NOT NULL
);
*/

CREATE TABLE bücher (
    id INT AUTO_INCREMENT PRIMARY KEY,
    buchtitel VARCHAR(100) NOT NULL,
    autor VARCHAR(100) NOT NULL,
    verlag VARCHAR(100) NOT NULL
);